package com.vaadin.designer.designertemplate;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoginTemplate extends CssLayout {
    protected Image logo;
    protected VerticalLayout login_wrapper;
    protected FormLayout login_form;
    protected Button login_button;
    protected CssLayout language_layout;
    protected NativeButton english;
    protected NativeButton german;
    protected NativeButton finnish;
    protected NativeButton swedish;

    public LoginTemplate() {
        Design.read(this);
    }
}
